/*
 * Bible edition — configuration. This is the ONLY file you normally edit.
 *
 * Why a .js file and not .json?  Browsers block reading local .json files when a
 * page is opened by double-clicking (file://). A <script> file always loads, so the
 * game works on any Windows/Mac PC with no web server and no installs.
 *
 * Paths are relative to this folder's index.html. PNG, JPG, WEBP and SVG all work.
 * The game engine itself lives in ../engine/ and is shared with the Classic edition.
 *
 * Adding Chinese: put the Chinese name in "title" below (the file NAME stays lowercase
 * ASCII — Chinese file names break on Windows and in URLs). Example:
 *   { image: "answers/noahs-ark.svg", title: "挪亞方舟" }
 */

// 18 tile pictures. If you list more than (gridSize*gridSize)/2, each game picks a random subset.
const ICONS = [
  "icons/01-dove.svg",     "icons/02-ark.svg",           "icons/03-rainbow.svg",
  "icons/04-tablets.svg",  "icons/05-crown.svg",         "icons/06-harp.svg",
  "icons/07-sling.svg",    "icons/08-bread.svg",         "icons/09-star.svg",
  "icons/10-lamb.svg",     "icons/11-lion.svg",          "icons/12-burning-bush.svg",
  "icons/13-oil-lamp.svg", "icons/14-scroll.svg",        "icons/15-grapes.svg",
  "icons/16-wheat.svg",    "icons/17-cross.svg",         "icons/18-big-fish.svg"
];

// Hidden answer pictures. One is chosen at random each game (never the same twice in a row).
// "title" is what the host sees when peeking (P) and what is shown on the final reveal.
const ANSWERS = [
  { image: "answers/noahs-ark.svg",         title: "Noah's Ark" },
  { image: "answers/david-and-goliath.svg", title: "David and Goliath" },
  { image: "answers/moses-red-sea.svg",     title: "Moses parts the Red Sea" },
  { image: "answers/jonah-big-fish.svg",    title: "Jonah and the big fish" },
  { image: "answers/daniel-lions-den.svg",  title: "Daniel in the lions' den" },
  { image: "answers/adam-and-eve.svg",      title: "Adam and Eve" },
  { image: "answers/baby-jesus-manger.svg", title: "Baby Jesus in the manger" },
  { image: "answers/josephs-coat.svg",      title: "Joseph's coat of many colours" },
  { image: "answers/samson.svg",            title: "Samson" },
  { image: "answers/zacchaeus.svg",         title: "Zacchaeus in the tree" }
];

window.GAME_CONFIG = {
  title: "Pattern Match - Bible Edition",

  // 6 x 6 = 36 tiles = 18 pairs. Must give an even number of tiles.
  gridSize: 6,

  icons: ICONS,
  answers: ANSWERS,

  // Timing (milliseconds)
  flipBackDelayMs: 1200,   // how long a wrong pair stays visible
  clearDelayMs: 700,       // pause before a matched pair fades away to show the answer

  // Sound (everything is generated by the browser — no audio files)
  sound: true,             // sound effects on at start (toggle in game with M)
  music: false,            // background music on at start (toggle in game with B)
  volume: 0.8              // overall volume, 0.0 - 1.0
};
