/*
 * Scripture edition (經文配對) — configuration. This is the ONLY file you normally edit.
 *
 * 7 x 7 board: 48 numbered tiles hold 24 pairs of short Bible phrases, and the centre
 * cell stays empty. The two halves of a pair are DIFFERENT texts that belong together
 * (真理 goes with 束腰帶子), so the audience has to know the verse to spot a match.
 *
 * Editing the pairs: change scripture/pairs.csv (number, left text, right text), then run
 *     python3 tools/csv_to_pairs.py scripture/pairs.csv scripture/config.js
 * or edit the PAIRS list below by hand. If you list more pairs than the board needs,
 * each game picks a random 24.
 *
 * Why a .js file and not .json?  Browsers block reading local files when the page is
 * opened by double-clicking (file://). A <script> file always loads.
 */

// PAIRS:BEGIN — generated from pairs.csv by tools/csv_to_pairs.py
const PAIRS = [
  ["真理",   "束腰帶子"],
  ["公義",   "護心鏡"],
  ["福音",   "走路的鞋"],
  ["信德",   "籐牌"],
  ["救恩",   "頭盔"],
  ["神的道",  "寶劍"],
  ["愛子",   "首生的"],
  ["萬有",   "靠他做"],
  ["以巴弗",  "忠心執事"],
  ["愛心",   "聯絡全德"],
  ["行不義",  "受報應"],
  ["耶穌",   "至寶"],
  ["萬事",   "糞土"],
  ["忘後",   "力前"],
  ["標竿",   "直跑"],
  ["加我力量", "凡事能作"],
  ["不是勉強", "乃是甘心"],
  ["活是基督", "死有益處"],
  ["貪圖榮耀", "全心謙卑"],
  ["友阿爹",  "循都基"],
  ["同心合意", "興旺福音"],
  ["脫去救人", "穿上新人"],
  ["為奴的",  "自主的"],
  ["耶數",   "猶士都"]
];
// PAIRS:END

// Hidden answer pictures. One is chosen at random each game (never the same twice in a row).
// "title" is shown to the host on peek (P) and on the final reveal.
const ANSWERS = [
  { image: "answers/noahs-ark.svg",         title: "挪亞方舟" },
  { image: "answers/david-and-goliath.svg", title: "大衛與歌利亞" },
  { image: "answers/moses-red-sea.svg",     title: "摩西過紅海" },
  { image: "answers/jonah-big-fish.svg",    title: "約拿與大魚" },
  { image: "answers/daniel-lions-den.svg",  title: "但以理在獅子坑" },
  { image: "answers/adam-and-eve.svg",      title: "亞當和夏娃" },
  { image: "answers/baby-jesus-manger.svg", title: "耶穌降生在馬槽" },
  { image: "answers/josephs-coat.svg",      title: "約瑟的彩衣" },
  { image: "answers/samson.svg",            title: "參孫" },
  { image: "answers/zacchaeus.svg",         title: "撒該爬上桑樹" }
];

window.GAME_CONFIG = {
  title: "經文配對遊戲",

  // 7 x 7 = 49 cells. An odd size leaves the centre empty, so 48 tiles = 24 pairs.
  gridSize: 7,

  pairs: PAIRS,            // text pairs (used instead of icons)
  answers: ANSWERS,

  // Timing (milliseconds) — a little longer than the picture editions,
  // so the room has time to read both cards.
  flipBackDelayMs: 2200,   // how long a wrong pair stays visible
  clearDelayMs: 1500,      // how long a matched pair stays before fading to show the answer

  // Sound (generated by the browser — no audio files)
  sound: true,
  music: false,
  volume: 0.8,

  // Everything the game writes on screen. {placeholders} are filled in by the engine.
  strings: {
    boardCleared: "全部配對完成！",
    boardClearedSub: "圖畫是甚麼？主持人：按 C 或 R",
    correct: "答對了！是「{title}」",
    correctSub: "共找到 {pairs}/{total} 對，用了 {turns} 回合",
    reveal: "答案是：「{title}」",
    revealSub: "按 N 開始新遊戲",
    peek: "答案：{title}",
    tileEntry: "第 {n} 格…",
    confirm: "再按一次確認",
    soundOn: "音效開", soundOff: "音效關",
    musicOn: "音樂開", musicOff: "音樂關"
  }
};
